sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gregfan/docker-tutorial -f Dockerfile.dev .

script: 
  - docker run -e CI=true gregfan/docker-tutorial npm run test