sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gregfan/docker-tutorial -f Dockerfile.dev .

script: 
  - docker run -e CI=true gregfan/docker-tutorial npm run test

deploy:
  provider: elasticbeanstalk
  edge: true   
  region: "us-east-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-597614504301"
  bucket_path: "docker"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"